class Nomenclature:

    def __init__(self, data: dict) -> None:
        self.id = data.get("id")
        self.organization_id = data.get("organizationId")
        self.external_id = data.get("externalId")
        self.external_code = data.get("externalCode")
        self.created = data.get("created")
        self.changed = data.get("changed")
        self.barcode = data.get("barcode")
        self.vendor_code = data.get("vendorCode")
        self.name = data.get("name")
        self.short_name = data.get("shortName") or 'n0 short_name'
        self.parent_id = data.get("parentId")
        self.vat_id = data.get("vatId")
        self.vat_value = data.get("vatValue")
        self.volume = data.get("volume")
        self.unit_code = data.get("unitCode")
        self.purchase_price = data.get("purchasePrice")
        self.selling_price = data.get("sellingPrice")
        self.picture = data.get("picture")
        self.weighted = data.get("weighted")
        self.grouped = data.get("grouped")
        self.focused = data.get("focused")
        self.container = data.get("container")
        self.payment_subject = data.get("paymentSubject")
        self.adults_only = data.get("adultsOnly")
        self.code = data.get("code")
        self.mark_type = data.get("markType")
        self.gtin = data.get("gtin")
        self.plu_code = data.get("pluCode")
        self.template = data.get("template")
        self.visible = data.get("visible")
        self.contractor_activity_type = data.get("contractorActivityType")
        self.contractor_id = data.get("contractorId")
        self.custom = data.get("custom")
        self.trade_object_relations = data.get("tradeObjectRelations")
        self.type = data.get("type")
        self.composite_goods = data.get("compositeGoods")
        self.barcodes = data.get("barcodes")
        self.country_code = data.get("countryCode")
        self.customs_declaration = data.get("customsDeclaration")
        self.description = data.get("description")
        self.picturesIds = data.get("picturesIds")
        self.application = data.get("application")
        self.nomenclature_features = data.get("nomenclatureFeatures")
        self.org_member_points = data.get("orgMemberPoints")
        self.global_nomenclature_id = data.get("globalNomenclatureId")
        self.quantum = data.get("quantum")
        self.global_category_id = data.get("globalCategoryId")
        self.global_nomenclature_moderation_status = data.get("globalNomenclatureModerationStatus")
        self.expiration = data.get("expiration")
        self.expiration_date = data.get("expirationDate")
        self.fifo = data.get("fifo")
        self.status = data.get("status")
        self.all_barcodes = data.get("allBarcodes")
        self.all_pictureIds = data.get("allPictureIds")

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        return isinstance(other, Nomenclature) and self.id == other.id
