class Nomenclature:

    def __init__(self, data) -> None:
        self.id = data["id"]
        self.organization_id = data["organizationId"]
        self.external_id = data["externalId"]
        self.external_code = data["externalCode"]
        self.created = data["created"]
        self.changed = data["changed"]
        self.barcode = data["barcode"]
        self.vendor_code = data["vendorCode"]
        self.name = data["name"]
        self.short_name = data["shortName"]
        self.parent_id = data["parentId"]
        self.vat_id = data["vatId"]
        self.vat_value = data["vatValue"]
        self.volume = data["volume"]
        self.unit_code = data["unitCode"]
        self.purchase_price = data["purchasePrice"]
        self.selling_price = data["sellingPrice"]
        self.picture = data["picture"]
        self.weighted = data["weighted"]
        self.grouped = data["grouped"]
        self.focused = data["focused"]
        self.container = data["container"]
        self.payment_subject = data["paymentSubject"]
        self.adults_only = data["adultsOnly"]
        self.code = data["code"]
        self.mark_type = data["markType"]
        self.gtin = data["gtin"]
        self.plu_code = data["pluCode"]
        self.template = data["template"]
        self.visible = data["visible"]
        self.contractor_activity_type = data["contractorActivityType"]
        self.contractor_id = data["contractorId"]
        self.custom = data["custom"]
        self.trade_object_relations = data["tradeObjectRelations"]
        self.type = data["type"]
        self.composite_goods = data["compositeGoods"]
        self.barcodes = data["barcodes"]
        self.country_code = data["countryCode"]
        self.customs_declaration = data["customsDeclaration"]
        self.description = data["description"]
        self.picturesIds = data["picturesIds"]
        self.application = data["application"]
        self.nomenclature_features = data["nomenclatureFeatures"]
        self.org_member_points = data["orgMemberPoints"]
        self.global_nomenclature_id = data["globalNomenclatureId"]
        self.quantum = data["quantum"]
        self.global_category_id = data["globalCategoryId"]
        self.global_nomenclature_moderation_status = data["globalNomenclatureModerationStatus"]
        self.expiration = data["expiration"]
        self.expiration_date = data["expirationDate"]
        self.fifo = data["fifo"]
        self.status = data["status"]
        self.all_barcodes = data["allBarcodes"]
        self.all_pictureIds = data["allPictureIds"]

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        return isinstance(other, Nomenclature) and self.id == other.id